# Made from project quay docker-compose.yaml
# https://github.com/quay/quay/blob/master/docker-compose.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-quad-db-data-pvc
  labels:
    app: quay-quad
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quay-quad-db-cm
  labels:
    app: quay-quad
data:
  pg_bootstrap.sql: |
    CREATE EXTENSION pg_trgm;
---
apiVersion: v1
kind: Pod
metadata:
  name: quay-quad-pod
  labels:
    app: quay-quad
spec:
  volumes:
    - name: db-config
      configMap:
        name: quay-quad-db-cm
    - name: db-data
      persistentVolumeClaim:
        claimName: quay-quad-db-data-pvc
  containers:
  - name: quay-quad-redis
    image: docker.io/library/redis:7.4.2
    ports:
    - redisPort: 6379
  - name: quay-quad-pgsql
    image: docker.io/library/postgres:12.1
    env:
    - name: POSTGRES_USER
      value: "quay"
    - name: POSTGRES_PASSWORD
      value: "quay"
    - name: POSTGRES_DB
      value: "quay"
    ports:
    - pgsqlPort: 5432
    volumeMounts:
    - name: db-config
      mountPath: /docker-entrypoint-initdb.d/pg_bootstrap.sql
      subPath: pg_bootstrap.sql
    - name: db-data
      mountPath: /var/lib/postgresql/data
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: quay-quad
# spec:
#   containers:
#   - name: quay
#     image: quay.io/projectquay/quay:3.13.4
#     env:
#       QUAY_VERSION: local-dev
#       QUAY_HOTRELOAD: "true"
#       DEBUGLOG: "true"
#       IGNORE_VALIDATION: "true"
#       QUAYRUN: /tmp
#       WORKER_COUNT_UNSUPPORTED_MINIMUM: "1"
#       WORKER_COUNT: "1"    # volumeMounts:
    # - name: wordpress-persistent-storage
    #   mountPath: /var/www/html
    # resources:
    #   requests:
    #     memory: "64Mi"
    #     cpu: "250m"
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
  # - name: envoy
  #   image: docker.io/envoyproxy/envoy:v1.25.0
  #   volumeMounts:
  #   - name: config-volume
  #     mountPath: /etc/envoy
  #   - name: certificates
  #     mountPath: /etc/envoy-certificates
  #   env:
  #   - name: ENVOY_UID
  #     value: "0"
  #   resources:
  #     requests:
  #       memory: "64Mi"
  #       cpu: "250m"
  #     limits:
  #       memory: "128Mi"
  #       cpu: "500m"
  # volumes:
  # - name: quay-pv
  #   persistentVolumeClaim:
  #     claimName: pg-pv-claim

